### ISSUE TITLE
OAuth2: State missing (mandatory in Ory Hydra)

### ISSUE THREAD

**Issue by Brutus5000** [julianlam/nodebb-plugin-sso-oauth#31]
I'm trying to move my nodebb instance from a custom OAuth2 implementation to [Ory Hydra](https://github.com/ory/hydra).
Unfortunately the login fails with an error `Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.`

I found a similar issue also with passport [here](https://github.com/hackmdio/codimd/pull/1512/files), but applying the `state: true` to the strategies.push [here](https://github.com/julianlam/nodebb-plugin-sso-oauth/blob/master/library.js#L151) did not solve the issue.

Any ideas what could cause this?

**Comment by julianlam** [comment]
Hi Brutus! Apologies for the delay, my email inbox is quite lengthy due to various family commitments :smile: 

Can you tell me more about that error, is it coming from Ory Hydra?

According to [this document](https://auth0.com/docs/protocols/state-parameters), the `state` parameter is "... to mitigate CSRF attacks by using a unique and non-guessable value... You send a random value when starting an authentication request and validate the received value when processing the response."

This is how NodeBB uses the `state` value, but there are additional configuration options in case someone wants to hook up to a non-standards-compliant OAuth2 provider (but that's neither here nor there).

NodeBB **core** handles this transparently. We [send in a randomly generated `state` value](https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L108) and [check for it afterwards](https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L124) to ensure that the person accessing the callback was the same person who initiated the login attempt.

**That said** -- I did accidentally introduce a regression in NodeBB v1.16.2 (and is present even in v1.17.1) that meant `state` was opt-in instead of opt-out, maybe this is something that applies here. [It is fixed in latest master](https://github.com/NodeBB/NodeBB/commit/a2400f6baff44cb2996487bcd0cc6e2acc74b3d4)

Can you try with the latest master of NodeBB and see if this is resolved? `state` is automatically handled then.

**Comment by Brutus5000** [comment]
Hi @julianlam,

thanks for your response. Yes, the error log above is from the Ory Hydra log.
I am still running on v1.16.2. I will do the upgrade first and then try again. Might take some time though.

**Comment by Brutus5000** [comment]
After a lot of investigations and some broken docker images in the v1.18 release serious we finally upgrade to 1.18.5 and it's working again.
